---
title: "p8105_hw1_hy2580"
author: "Haokun Yuan"
date: "9/17/2018"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Problem 1

Create data frame:

```{r}
set.seed(1)
vec_numeric = runif(10,0,5)
vec_logical = c(TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE)
vec_char = c("It", "is", "hard", "to", "think", "of", "so", "many", "different", "characters")
vec_factor = factor(c("female", "female", "female","female", "female", "male", "male", "male", "male", "male"))

tibble(vec_numeric, vec_logical, vec_char, vec_factor)
```

Take mean of the variable:

```{r}
mean_numeric = mean(vec_numeric)
mean_logical = mean(vec_logical)
mean_char = mean(vec_char)
mean_factor = mean(vec_factor)
```
The mean of vec_numeric and vec_logical can be taken, while the mean of vec_char and vec_factor cannot.

We can only calculate the mean of variables with numeric values, logical variables can calculated since they can be interpret as 1s and 0s,

Convert variables:

```{r, eval = FALSE}
num_logical = as.numeric(vec_logical)
num_char = as.numeric(vec_char)
num_factor = as.numeric(vec_factor)
```

```{r}
as.factor(vec_char)
as.numeric(as.factor(vec_char))
as.numeric(vec_factor)
```



